env: dev
CATALOGUE_HOST: catalogue.backend-{{ env }}.srinunayak.online
USER_HOST: user.backend-{{ env }}.srinunayak.online
CART_HOST: cart.backend-{{ env }}.srinunayak.online
SHIPPING_HOST: shipping.backend-{{ env }}.srinunayak.online
PAYMENT_HOST: payment.backend-{{ env }}.srinunayak.online