
  - name: python setup
    include_role:
     name: common
     tasks_from: python_setup
     
  - name: app_setup
    include_role:
     name: common
     tasks_from: app_setup



  - name: set the payment service
    ansible.builtin.copy:
     src: payment.service
     dest: /etc/systemd/system/payment.service
  
  - name: enable and start payment service
    ansible.builtin.service:
     name: payment
     state: started
     enabled: yes

  
