- name: disabled nodejs latest version and enabled older version
  ansible.builtin.command: dnf module disable nodejs -y
  ansible.builtin.command: dnf module enable nodejs:20 -y

- name: install nodejs
  ansible.builtin.dnf:
   name: nodejs
   state: present

- name: installaing npm dependencies
  community.general.npm:
   path: /app
