
- name: setup the {{ component }} service
  ansible.builtin.template:
   src: "{{ component }}.service.j2"
   dest: "/etc/systemd/system/{{ component }}.service"

- name: reload the deamon
  ansible.builtin.systemd_service:
   daemon_reload: true

- name: enable and start the {{ component }}
  ansible.builtin.service:
   name: "{{ component }}"
   state: started
   enabled: yes